import "./globals.css";
import Header from "./_components/Header";

export const metadata = {
  title: "Cleaning Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
