import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";

const inter = Outfit({ subsets: ["latin"] });
export const metadata = {
  title: "Cleaning Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <div>
            <Header />
            {children}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
